Monocypher ed25519 optional module added
eugene-eeo/monocypher-py pull request #2
Opened 2022-01-16 11:49 UTC by covert-encryption

2022-01-17 22:35 UTC, covert-encryption commented
Could also upgrade the monocypher.c/h files from Github, as there have been some fixes. But maybe that (and renaming the folder not to contain the version number) is for another PR then, or possibly even for another upstream release.

2022-01-18 23:03 UTC, eugene-eeo commented
@covert-encryption, just one minor point to address and I'll merge the MR.

other stuff lgtm.

2022-01-19 10:13 UTC, covert-encryption commented
I think a few more PRs might be in order for the next release. I am not in a particular hurry and won't need 0.0.3 right now (our project uses a plain-python implementation of elliptic curves that gets the job done).

Upstream Monocypher are now considering the inclusion of Signal's XEdDSA signatures, and if they do that, it would be awesome to have it on the Python bindings as well.

Also, if there is a new release, the amount of API breakage needs to be considered. If your own project is the only user of this, it shouldn't be a concern, but this has been on PyPI for a while so we don't know how many others are using it, although we have the benefit that the low level API is kind of hidden in your implementation so it is unlikely that changing it is going to be noticed by anyone.

In any case, I expect to be doing a few more PRs to add more of the stuff I've already implemented prior to your answer. In particular, the docstrings and the ability to give the return buffer as `ret=` kwarg on all the functions (`ret_something` on functions that return more than one buffer).

Potentially also the self-wiping return type should be included in the next release (used if no ret kwarg is given).

My current implementation is a pair of plain Python classes using the `__del__` method to do the wiping, and unfortunately this way it cannot be very compatible with anything (custom types cannot derive from `memoryview` which would be helpful to allow it to be at least a bytes-like type). One hacky Python side solution is to derive from built-in `bytes` and wipe it on destructor (using Monocypher's wipe because CFFI doesn't check for read-only) but it is illegal and potentially breaks in some unexpected situations so I'd wish to avoid that.

Ideally a C extension type that `isinstance` of `bytes` should be created but I couldn't find any existing implementation of such, and I am not sure whether I want to dive into making one myself. The advantage would be compatibility with everything else in Python, including `pynacl` and `cryptography` which require their arguments to be instances of bytes (other bytes-like types are not accepted). This would also allow for locking the memory, so that keys never end up in swap or core dump files.

2022-01-19 10:19 UTC, covert-encryption commented
> @covert-encryption, just one minor point to address and I'll merge the MR.

Did you mean some point with the PR itself, not that of a new release? I see no comments on the PR.

2022-01-19 10:53 UTC, eugene-eeo requested changes

2022-01-19 10:53 UTC, eugene-eeo commented on src/monocypher-3.1.2-src/optional/monocypher-ed25519.c
> +// Monocypher version __git__
minor point (but quite important for me)

can you ensure that you use the version from 3.1.2 (instead of from the upstream github repository). Reason being is that the sha256 sums didn't add up, and were initially cause for concern -- further inspection shows it's just the `__git__` vs `3.1.2`, but still :)

for reference, the source included in the master branch of this repo is exactly the same as the one in 3.1.2:

```
monocypher-py/
7d10bba489ae669a406e6842f717537053102a47f459469c8031c101ba2ae7b4  src/monocypher-3.1.2-src/monocypher.c
bb0106c0f0af10c08422f7a8d0edfcca5387d2547c67a59b0fdd94c27211287c  src/monocypher-3.1.2-src/monocypher.h
a696d1318586c3a8e0a3bab63f9b6c0f1ac0efd10b415a58d89a23a99e70575f  src/monocypher-3.1.2-src/optional/monocypher-ed25519.c
ff03210b6acdfb91bf694fd9cb8db6cdee837f2a0528e5c0209733a9a13de776  src/monocypher-3.1.2-src/optional/monocypher-ed25519.h

monocypher-3.1.2/ [downloaded from https://monocypher.org/download/monocypher-3.1.2.tar.gz]
7d10bba489ae669a406e6842f717537053102a47f459469c8031c101ba2ae7b4  src/monocypher.c
bb0106c0f0af10c08422f7a8d0edfcca5387d2547c67a59b0fdd94c27211287c  src/monocypher.h
966b68b699f238beeffddc9c5338facc67f80898af0304109681d6e5ab899d3a  src/deprecated/aead-incr.c
f0b339740f1cd9b511c4d8269e550f3d05dd4697a173683c80e3a3226d990656  src/deprecated/aead-incr.h
c16b97852dcae94a29e68e50ec8ee39e27eb2275c84b2df4c6029bf11bc864f0  src/deprecated/chacha20.c
7c6a20796170fe90c9ee4c1e860d4a3b7a0a77d25132ceaf24466f6c0956512f  src/deprecated/chacha20.h
4914571bfed6ffb81d75343f6e9e318ed7c97a23e493ba041270e00d0102d2e1  src/optional/monocypher-ed25519.c
686b79791a55d41a7b448926aabb5da14205de63e03f20b9e52e2155b115ca74  src/optional/monocypher-ed25519.h
```

2022-01-19 21:31 UTC, covert-encryption commented
Looks like it should now work but the CI is running too slowly. Good catch on the git versions of the optional files. Hopefully we'll see another Monocypher release soon, so that using the git version (the direction I intended) could be avoided.

2022-01-19 23:04 UTC, eugene-eeo commented
lgtm, thanks 😄

2022-01-19 23:04 UTC, merged