elligator2: expose low-level bindings
eugene-eeo/monocypher-py pull request #4
Opened 2022-07-10 22:01 UTC by cfcs

This PR exposes the low-level Elligator 2 functions `crypto_hidden_key_pair`, `crypto_hidden_to_curve`, `crypto_curve_to_hidden`.

There's no high-level wrapper, and no `.rst` documentation, but I think it's still useful. :-)

I also loosened the constraint on the `hypothesis` library in `requirements.txt` to avoid forcing a downgrade.

2022-07-15 08:10 UTC, eugene-eeo commented
will have a look later tonight :)

2022-07-15 20:58 UTC, eugene-eeo requested changes

2022-07-15 20:58 UTC, eugene-eeo commented on src/monocypher/bindings/crypto_hidden.py
> +#def curve_to_hidden(your_pk:PublicKey, tweak:bytes) -> Optional[bytes]:
please remove the C-definitions on top, as well as the type hints (they're not used elsewhere in the library).

2022-07-15 20:58 UTC, eugene-eeo commented on src/monocypher/bindings/crypto_hidden.py
> +    if 0 != lib.crypto_curve_to_hidden(hidden, curve, tweak):
`if lib.crypto_curve_to_hidden(...) != 0` instead of the yoda conditionals please.

2022-07-15 20:58 UTC, eugene-eeo commented on tests/test_hidden.py
> +    assert len(seed) == 32
I think you don't have to test that seed length works :sweat_smile: 
since you'll be using the `ensure_length` functions to verify it anyways.

2022-07-15 20:58 UTC, eugene-eeo commented on tests/test_hidden.py
> +    tweak = (hidden_pk[31] & 0b11000000)
you'll have to forgive my lack of knowledge if its obvious;
where did this come from?

2022-07-15 20:58 UTC, eugene-eeo commented on src/monocypher/bindings/crypto_hidden.py
> +#from monocypher.public import PublicKey, PrivateKey
please remove the commented code.

2022-08-11 19:56 UTC, cfcs commented on tests/test_hidden.py
> +    tweak = (hidden_pk[31] & 0b11000000)
Sorry, that was totally not obvious. I added a comment explaining it.

2022-08-11 19:57 UTC, cfcs commented on tests/test_hidden.py
> +    assert len(seed) == 32
It's there to test that `ensure_length` is there :)

2022-08-11 19:58 UTC, cfcs commented
I missed the notification about your comments. I've revised the patchset and uploaded a commit that attempts to address your points @eugene-eeo.

2022-08-27 21:30 UTC, eugene-eeo commented
thanks for the PR!
and sorry for the late response
i've merged it after some additions.

2022-08-27 21:30 UTC, merged